# Generated by Django 4.0.5 on 2022-06-30 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_mark', models.CharField(max_length=20, unique=True, verbose_name='Марка автомобиля')),
            ],
            options={
                'verbose_name': 'Марка автомобиля',
                'verbose_name_plural': 'Марки автомобилей',
                'ordering': ['car_mark'],
            },
        ),
        migrations.CreateModel(
            name='CarModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_models', models.CharField(max_length=40, verbose_name='модель автомобиля')),
                ('car_mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avto.carmark', verbose_name='Марка автомобиля')),
            ],
            options={
                'verbose_name': 'Модель автомобиля',
                'verbose_name_plural': 'Модели автомобилей',
                'ordering': ['car_models'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=20, verbose_name='Зона')),
            ],
            options={
                'verbose_name': 'Зона',
                'verbose_name_plural': 'Зоны',
                'ordering': ['zone'],
            },
        ),
        migrations.CreateModel(
            name='Сhange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.CharField(max_length=20, verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'ordering': ['change'],
            },
        ),
        migrations.CreateModel(
            name='Сars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=10, unique=True, verbose_name='Номер автомобиля')),
                ('car_color', models.CharField(max_length=15, verbose_name='Цвет автомобиля')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО владельца')),
                ('organization', models.CharField(max_length=255, verbose_name='Организация владельца')),
                ('position', models.CharField(max_length=255, verbose_name='Должность владельца')),
                ('сontact_details', models.CharField(max_length=255, verbose_name='Контактный данные')),
                ('date', models.DateTimeField()),
                ('car_mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avto.carmark', verbose_name='Марка автомобиля')),
                ('car_models', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avto.carmodels', verbose_name='Модель автомобиля')),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avto.сhange', verbose_name='Смена')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avto.type', verbose_name='Тип')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avto.zone', verbose_name='Зона')),
            ],
        ),
    ]
