# Generated by Django 4.0.5 on 2022-06-30 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmark',
            options={'verbose_name': 'Марка автомобиля', 'verbose_name_plural': 'Марки автомобилей'},
        ),
        migrations.AlterModelOptions(
            name='carmodels',
            options={'verbose_name': 'Модель автомобиля', 'verbose_name_plural': 'Модели автомобилей'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'verbose_name': 'Зона', 'verbose_name_plural': 'Зоны'},
        ),
        migrations.AlterModelOptions(
            name='сars',
            options={'ordering': ['car_number'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='сhange',
            options={'verbose_name': 'Смена', 'verbose_name_plural': 'Смены'},
        ),
        migrations.AddField(
            model_name='сars',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='сars',
            name='date',
            field=models.DateTimeField(verbose_name='Срок'),
        ),
    ]
