# Generated by Django 4.0.5 on 2022-07-01 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avto', '0003_сars_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сars',
            name='author',
            field=models.ForeignKey(default='auth.User', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
