# Generated by Django 4.0.5 on 2022-07-01 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avto', '0004_alter_сars_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=30, verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['organization'],
            },
        ),
        migrations.AlterField(
            model_name='сars',
            name='author',
            field=models.ForeignKey(default='auth.User', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='сars',
            name='сontact_details',
            field=models.CharField(max_length=255, verbose_name='Контактные данные'),
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees', models.CharField(max_length=100, verbose_name='Сотрудники')),
                ('position', models.CharField(max_length=255, verbose_name='Должность сотрудника')),
                ('сontact_details', models.CharField(max_length=255, verbose_name='Контактные данные')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avto.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
