# Generated by Django 4.0.5 on 2022-07-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0005_organization_alter_сars_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employees',
            field=models.CharField(max_length=255, verbose_name='Сотрудники'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization',
            field=models.CharField(max_length=255, verbose_name='Организация'),
        ),
    ]
