# Generated by Django 4.0.5 on 2022-07-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0006_alter_employees_employees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization',
            field=models.CharField(max_length=255, unique=True, verbose_name='Организация'),
        ),
    ]
