# Generated by Django 4.0.5 on 2022-07-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0007_alter_organization_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='сars',
            name='allowed',
            field=models.BooleanField(default=True, verbose_name='Разрешено'),
        ),
    ]
